apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: node-helloworld
  name: node-helloworld
  namespace: app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: node-helloworld
        tier: backend
    spec:
      containers:
      - name: node-helloworld
        image: arielweinberger/node-helloworld:10.0.0-10
        ports:
        - containerPort: 3000
  