apiVersion: v1
kind: Service
metadata:
  name: node-helloworld
  namespace: app
spec:
  type: NodePort
  selector:
    app: node-helloworld
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
